name:                aoc2022
version:             0.1.0.0
github:              "RileyEv/aoc2022"
license:             BSD3
author:              "Riley Evans"
maintainer:          "riley@rly.rocks"
copyright:           "2022 Riley Evans"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/RileyEv/aoc2022#readme>

dependencies:
- base >= 4.7 && < 5
- template-haskell
- extra
- containers
- split
- parsec
- vector
- megaparsec
- Unique
- array

default-extensions:
- TemplateHaskell

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -fprof-auto
- -fprof-cafs
- -fforce-recomp

library:
  source-dirs: src

executables:
  aoc2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -fprof-auto
    - -fprof-cafs
    - -fforce-recomp
    dependencies:
    - aoc2022

tests:
  aoc2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2022
    - tasty
    - tasty-hunit
    - HUnit
    - containers
    - vector

benchmarks:
  aoc2022-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - aoc2022
    - criterion
